### ISSUE TITLE
findAll returns the type of query not the documents's type

### ISSUE THREAD

**Issue by cht8687** [exqir/mongad#9]
Hi guys, 

I tried use `findMany("users", { enabled: { $in: ['feature_enabled'] } } ) (getDb("db")(client))()` 

seems the return type is:

```
Promise<E.Either<MongoError, {
    enabled: string | {
        $in: string[];
    };
}[]>>
```
but findMany should return the `Users` type.... apparently, it's taking query's type.
so it's complaining that some basic fields in the document data, not existing in ` {
    enabled: string | {
        $in: string[];
    };
}`

it appears that:

```
export type FilterQuery<T> = {
    [P in keyof T]?: Condition<T[P]>;
} &
    RootQuerySelector<T>
```
in Mongoldb types definition. 

is there any solution for this?

**Comment by exqir** [comment]
Hey,

you will need to provide your `User` type as a generic to findMany e.g. 

```
type User = {
  enabled: string[]
 // rest of your user object
}

findMany<User>("users", { enabled: { $in: ['feature_enabled'] } } ) (getDb("db")(client))()
``` 

If you don't provide it the type will be inferred and the query is the only type information available, so that is the only thing TypeScript knows about your user type.

**Comment by cht8687** [comment]
thanks, @exqir didn't notice that missed it. Great lib.
